Fix: Inherit `StableDiffusionXLLoraLoaderMixin` instead of `StableDiffusionLoraLoaderMixin`
This bug caused the error upon loading LoRA:
```
  File "/workspace/DMD2/venv/lib/python3.10/site-packages/peft/tuners/tuners_utils.py", line 509, in inject_adapter
    raise ValueError(
ValueError: Target modules {'2.1.transformer_blocks.8.ff.net.2', '2.1.transformer_blocks.6.attn2.to_v',
...
, '5.1.transformer_blocks.1.attn1.to_k'} not found in the base model. Please check the target modules and try again.
```